server:
  port: ${PORT:8080}
  tomcat.threads.max: ${SERVER_MAX_THREADS:2000}

spring:
  application:
    name: wishlist
  main:
    banner-mode: off
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wishlist_db
  docker:
    compose:
      enabled: true
      file: docker-compose.yml

management:
  endpoints:
    web.exposure.include: health,metrics
  endpoint:
    health:
      probes.enabled: true
      group:
        liveness.include: livenessState
        readiness.include: readinessState
      show-components: always
      show-details: always

wishlist:
  limit:
    size: ${WISHLIST_LIMIT_SIZE:20}